In [3]:
import numpy as np


In [9]:
a = np.array([1, 2, 3], dtype='int16')
b = np.array([[3, 5.2, 4], [2, 5.5, 8]])

In [15]:
# Get Dimension
a.ndim

# Get Shape
b.shape

# Get type
a.dtype

# Get Size
a.size

a = np.array

3

In [17]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [18]:
a[1, -2]

13

In [20]:
# Get a specific row or column
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
# [start:end:step]
a[0,1:6:2]

array([2, 4, 6])

In [23]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [24]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.72677941, 0.12053716],
       [0.30111683, 0.32094936],
       [0.79584131, 0.20982846],
       [0.09292109, 0.17625055]])

In [25]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 6,  6,  6],
       [ 2, -3,  3],
       [ 7,  6,  1]])

In [ ]:
# Copy
b = a.copy()